name: gexd
description: A sample command-line application.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  args: ^2.7.0
  cli_completion: ^0.5.1
  mason_logger: ^0.3.3
  pub_updater: ^0.5.0
  build_version: ^2.1.3
  interact: ^2.2.0
  yaml: ^3.1.3
  meta: ^1.17.0
  mason: ^0.1.1

dev_dependencies:
  build_runner: ^2.9.0
  build_verify: ^3.1.1
  coverage: ^1.15.0
  io: ^1.0.5
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.25.6


executables:
  gexd: gexd
