name: gexd
description: A powerful CLI tool to scaffold Flutter projects using GetX with SOLID principles and Clean Architecture patterns. Generate complete project structures, models, screens, repositories, services, and more with typed model integration.
version: 0.0.3
homepage: https://github.com/altwaireb/gexd
repository: https://github.com/altwaireb/gexd
documentation: https://gexd-docs.gitbook.io/gexd-cli-documentation
issue_tracker: https://github.com/altwaireb/gexd/issues
funding:
  - https://github.com/sponsors/altwaireb

environment:
  sdk: ^3.8.3

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  args: ^2.7.0
  cli_completion: ^0.5.1
  mason_logger: ^0.3.3
  pub_updater: ^0.5.0
  build_version: ^2.1.3
  interact: ^2.2.0
  yaml: ^3.1.3
  meta: ^1.17.0
  mason: ^0.1.1
  analyzer: ^8.2.0
  grammer: ^1.0.3
  http: ^1.3.0

dev_dependencies:
  build_runner: ^2.9.0
  build_verify: ^3.1.1
  coverage: ^1.15.0
  io: ^1.0.5
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.25.6


executables:
  gexd: gexd
